
# ADB
BPROP "system" "ro.adb.secure" "0"
BPROP "vendor" "ro.adb.secure" "0"
						   					   
		

# AstroROM props		
ROM_BUILD_ID="$(GET_PROP "system" "ro.build.display.id")"


if [[ "$ROM_BUILD_ID" == *Astro* ]]; then
    ASTROROM_PROP="$ROM_BUILD_ID"
else
    ASTROROM_PROP="AstroROM ${ROM_VERSION} [${ROM_BUILD_ID}]"
fi

BPROP "system" "ro.build.display.id" "$ASTROROM_PROP"					  
					
	
LOG_BEGIN "Generating Astro Build Info"

TIMESTAMP="$(date +"%d %B %Y – %I:%M %p")"

ANDROID_VERSION="$(GET_PROP "system" "ro.build.version.release")"
API_LEVEL="$(GET_PROP "system" "ro.build.version.sdk")"

# Write to astro.prop
cat <<EOF > "$WORKSPACE/system/system/astro.prop"
# 
#  AstroROM auto generated prop
#
#  This file is automatically generated by the
#  ProjectAstronut ROM compiler utility.
#  Do not edit manually unless you know what you’re doing.
#

TIMESTAMP        = $TIMESTAMP
DEVICE_MODEL     = $MODEL_NAME
DEVICE_CODENAME  = $CODENAME
ANDROID_VERSION  = $ANDROID_VERSION
API_LEVEL        = $API_LEVEL

EOF

LOG_END "Astro Build Info generated successfully"
